# SPDX-License-Identifier: GPL-2.0-or-later
"""Project ``credibility/<id>.json`` + ``report_provenance.json``.

Each per-candidate credibility report becomes a ``File`` referenced
from the candidate's ``CreateAction.result`` via
:func:`apmode.bundle.rocrate.entities.backend.add_backend_create_action`
— this module only adds the File entities and the cross-reference.
"""

from __future__ import annotations

from pathlib import Path  # noqa: TC003 — runtime type in function signatures
from typing import Any

from apmode.bundle.rocrate import vocab
from apmode.bundle.rocrate.entities._common import (
    file_entity,
    load_json_optional,
    merge_list_property,
    upsert,
)


def add_credibility_reports(
    graph: list[dict[str, Any]],
    bundle_dir: Path,
) -> list[str]:
    """Project ``credibility/<id>.json`` files as ``File`` entities.

    For every candidate with both a CreateAction entity in the graph
    and a credibility JSON on disk, attach the credibility File to the
    CreateAction's ``result`` list.

    Returns the list of File ``@id``s added.
    """
    d = bundle_dir / "credibility"
    if not d.is_dir():
        return []
    added: list[str] = []
    for p in sorted(d.glob("*.json")):
        candidate_id = p.stem
        payload = load_json_optional(p) or {}
        context_of_use = payload.get("context_of_use")
        description = f"Credibility report for {candidate_id}" + (
            f" — {context_of_use}" if isinstance(context_of_use, str) else ""
        )
        entity = file_entity(
            bundle_dir,
            p,
            name=f"Credibility report ({candidate_id})",
            extra={
                "description": description,
                "additionalType": vocab.CREDIBILITY_REPORT,
            },
        )
        upsert(graph, entity)
        root = upsert(graph, {"@id": "./", "@type": "Dataset"})
        merge_list_property(root, "hasPart", {"@id": entity["@id"]})

        # Link to this candidate's CreateAction if it exists
        action_id = f"#backend-create-{candidate_id}"
        for ent in graph:
            if ent.get("@id") == action_id:
                merge_list_property(ent, "result", {"@id": entity["@id"]})
                break
        added.append(str(entity["@id"]))
    return added


def add_report_provenance(
    graph: list[dict[str, Any]],
    bundle_dir: Path,
    root_id: str = "./",
) -> str | None:
    path = bundle_dir / "report_provenance.json"
    if not path.is_file():
        return None
    payload = load_json_optional(path) or {}
    generator = payload.get("generator") or "APMODE report generator"
    entity = file_entity(
        bundle_dir,
        path,
        name="Report provenance",
        extra={"description": f"Generated by {generator}"},
    )
    upsert(graph, entity)
    root = upsert(graph, {"@id": root_id, "@type": "Dataset"})
    merge_list_property(root, "hasPart", {"@id": entity["@id"]})
    return str(entity["@id"])
