# SPDX-License-Identifier: GPL-2.0-or-later
"""Project ``credibility/<id>.json`` + ``report_provenance.json``.

Each per-candidate credibility report becomes a ``File`` referenced
from the candidate's ``CreateAction.result`` via
:func:`apmode.bundle.rocrate.entities.backend.add_backend_create_action`
— this module only adds the File entities and the cross-reference.
"""

from __future__ import annotations

from pathlib import Path  # noqa: TC003 — runtime type in function signatures
from typing import Any

from apmode.bundle.rocrate import vocab
from apmode.bundle.rocrate.entities._common import (
    file_entity,
    load_json_optional,
    merge_list_property,
    upsert,
)


def add_credibility_reports(
    graph: list[dict[str, Any]],
    bundle_dir: Path,
) -> list[str]:
    """Project ``credibility/<id>.json`` files as ``File`` entities.

    A credibility report is only projected when its corresponding
    ``#backend-create-<id>`` CreateAction is already in the graph —
    credibility is candidate-scoped provenance, so a dangling
    credibility File without an action to attach to would leave the
    crate with orphaned evidence that could not be traced to a
    candidate run. The caller (the projector) must project
    :mod:`apmode.bundle.rocrate.entities.backend` before credibility.

    Returns the list of File ``@id``s added (may be empty).
    """
    d = bundle_dir / "credibility"
    if not d.is_dir():
        return []
    added: list[str] = []
    for p in sorted(d.glob("*.json")):
        candidate_id = p.stem

        action_id = f"#backend-create-{candidate_id}"
        candidate_action = next((e for e in graph if e.get("@id") == action_id), None)
        if candidate_action is None:
            # No backend result for this candidate — skip emission to
            # avoid an orphan credibility File. Preserves the invariant
            # that every credibility report is reachable from a
            # CreateAction in the graph.
            continue

        payload = load_json_optional(p) or {}
        context_of_use = payload.get("context_of_use")
        description = f"Credibility report for {candidate_id}" + (
            f" — {context_of_use}" if isinstance(context_of_use, str) else ""
        )
        entity = file_entity(
            bundle_dir,
            p,
            name=f"Credibility report ({candidate_id})",
            extra={
                "description": description,
                "additionalType": vocab.CREDIBILITY_REPORT,
            },
        )
        upsert(graph, entity)
        root = upsert(graph, {"@id": "./", "@type": "Dataset"})
        merge_list_property(root, "hasPart", {"@id": entity["@id"]})
        merge_list_property(candidate_action, "result", {"@id": entity["@id"]})
        added.append(str(entity["@id"]))
    return added


def add_report_provenance(
    graph: list[dict[str, Any]],
    bundle_dir: Path,
    root_id: str = "./",
) -> str | None:
    path = bundle_dir / "report_provenance.json"
    if not path.is_file():
        return None
    payload = load_json_optional(path) or {}
    generator = payload.get("generator") or "APMODE report generator"
    entity = file_entity(
        bundle_dir,
        path,
        name="Report provenance",
        extra={"description": f"Generated by {generator}"},
    )
    upsert(graph, entity)
    root = upsert(graph, {"@id": root_id, "@type": "Dataset"})
    merge_list_property(root, "hasPart", {"@id": entity["@id"]})
    return str(entity["@id"])
