# SPDX-License-Identifier: GPL-2.0-or-later
"""Project ``bom.cdx.json`` (CycloneDX SBOM) onto a File entity.

The SBOM is a *producer-side sidecar*: it is generated by
``apmode bundle sbom`` (or by CI/release tooling) and dropped into the
bundle directory *after* sealing. The bundle-digest computation in
:func:`apmode.bundle.emitter._compute_bundle_digest` explicitly excludes
``bom.cdx.json`` so the ``_COMPLETE`` sentinel remains valid regardless
of whether or when the SBOM is attached.

When present the projector adds a single ``File`` entity tagged with
``apmode:sbom`` and links it into the root Dataset's ``hasPart``. The
``encodingFormat`` uses the IANA media type for CycloneDX JSON so
downstream tooling (WorkflowHub, Zenodo, SBOM scanners) can dispatch
on the type without opening the file.
"""

from __future__ import annotations

from pathlib import Path  # noqa: TC003 — runtime type in function signatures
from typing import Any

from apmode.bundle.rocrate import vocab
from apmode.bundle.rocrate.entities._common import (
    file_entity,
    merge_list_property,
    upsert,
)

_SBOM_FILENAME = "bom.cdx.json"
_CYCLONEDX_MEDIA_TYPE = "application/vnd.cyclonedx+json"


def add_sbom(
    graph: list[dict[str, Any]],
    bundle_dir: Path,
    root_id: str = "./",
) -> str | None:
    """Project ``bom.cdx.json`` as a File entity + root ``hasPart`` link.

    Returns the ``@id`` of the File entity, or ``None`` if the SBOM is
    absent. This is the only path that projects the SBOM — callers
    should not hand-build File entities for it.
    """
    path = bundle_dir / _SBOM_FILENAME
    if not path.is_file():
        return None
    entity = file_entity(
        bundle_dir,
        path,
        name="CycloneDX SBOM (APMODE Python dependencies)",
        encoding_format=_CYCLONEDX_MEDIA_TYPE,
        extra={
            "additionalType": vocab.SBOM_TYPE,
            "description": (
                "CycloneDX Software Bill of Materials for the APMODE "
                "Python environment that produced this bundle."
            ),
        },
    )
    upsert(graph, entity)
    root = upsert(graph, {"@id": root_id, "@type": "Dataset"})
    merge_list_property(root, "hasPart", {"@id": entity["@id"]})
    return str(entity["@id"])


__all__ = ["add_sbom"]
