# SPDX-License-Identifier: GPL-2.0-or-later
# APMODE nlmixr2 estimation harness (ARCHITECTURE.md S4.2)
#
# Usage: Rscript harness.R <request.json> <response.json>
#
# Reads a typed request, runs nlmixr2 estimation, writes a typed response.
# All communication is file-based. stdout/stderr are for logging only.
#
# Security note: The R code evaluated here is generated by the APMODE DSL
# compiler (emit_nlmixr2), not user input. The DSL grammar constrains what
# can be expressed, and the semantic validator enforces safety invariants.

suppressPackageStartupMessages({
  library(jsonlite)
  library(nlmixr2)
})

args <- commandArgs(trailingOnly = TRUE)
if (length(args) != 2) {
  stop("Usage: Rscript harness.R <request.json> <response.json>")
}

request_path <- args[1]
response_path <- args[2]

# --- Helper functions (defined before use) ---

.capture_session_info <- function() {
  nlmixr2_ver <- tryCatch(
    as.character(packageVersion("nlmixr2")),
    error = function(e) "unknown"
  )
  pkg_versions <- sapply(loadedNamespaces(), function(p) {
    tryCatch(as.character(packageVersion(p)), error = function(e) "unknown")
  })

  list(
    r_version = paste0(R.version$major, ".", R.version$minor),
    nlmixr2_version = nlmixr2_ver,
    platform = R.version$platform,
    packages = as.list(pkg_versions)
  )
}


.extract_backend_result <- function(fit, method, req) {
  # Parameter estimates from fixed effects table
  params <- as.data.frame(fit$parFixedDf)
  param_list <- list()

  has_se <- "SE" %in% names(params)
  has_rse <- "%RSE" %in% names(params)

  for (i in seq_len(nrow(params))) {
    pname <- rownames(params)[i]
    se_val <- if (has_se && !is.na(params$SE[i])) params$SE[i] else NULL
    rse_val <- if (has_rse && !is.na(params$`%RSE`[i])) params$`%RSE`[i] else NULL
    param_list[[pname]] <- list(
      name = pname,
      estimate = params$Estimate[i],
      se = se_val,
      rse = rse_val,
      ci95_lower = NULL,
      ci95_upper = NULL,
      fixed = FALSE,
      # Classify: eta.* -> iiv, sigma/prop/add -> residual, else structural
      category = if (grepl("^eta\\.", pname)) "iiv"
                 else if (grepl("prop|add|sigma", pname, ignore.case = TRUE)) "residual"
                 else "structural"
    )
  }

  # ETA shrinkage
  shrinkage <- tryCatch({
    s <- fit$shrinkage
    if (is.null(s)) list() else as.list(s)
  }, error = function(e) list())

  # Convergence info — check multiple indicators for robustness across
  # SAEM/FOCEI/nlme methods (fit$message text varies by method)
  converged <- tryCatch({
    msg_ok <- !is.null(fit$message) && grepl("successful|converge", fit$message,
                                              ignore.case = TRUE)
    # Also check if objective function is finite (non-converged fits may have Inf)
    ofv_ok <- tryCatch(!is.null(fit$objDf$OBJF[1]) && is.finite(fit$objDf$OBJF[1]),
                       error = function(e) FALSE)
    msg_ok || ofv_ok
  }, error = function(e) FALSE)

  conv_meta <- list(
    method = method,
    converged = converged,
    iterations = if (!is.null(fit$niter)) as.integer(sum(fit$niter)) else 0L,
    gradient_norm = NULL,
    minimization_status = if (converged) "successful" else "terminated",
    wall_time_seconds = as.numeric(fit$time["elapsed"], units = "secs")
  )

  # GOF metrics
  gof <- tryCatch({
    cwres <- fit$CWRES
    list(
      cwres_mean = mean(cwres, na.rm = TRUE),
      cwres_sd = sd(cwres, na.rm = TRUE),
      outlier_fraction = mean(abs(cwres) > 4, na.rm = TRUE),
      obs_vs_pred_r2 = cor(fit$DV, fit$PRED, use = "complete.obs")^2
    )
  }, error = function(e) {
    list(cwres_mean = 0, cwres_sd = 1, outlier_fraction = 0, obs_vs_pred_r2 = NULL)
  })

  # Condition number
  cond_num <- tryCatch(fit$conditionNumber, error = function(e) NULL)

  # OFV, AIC, BIC
  ofv_val <- tryCatch(fit$objDf$OBJF[1], error = function(e) NULL)
  aic_val <- tryCatch(AIC(fit), error = function(e) NULL)
  bic_val <- tryCatch(BIC(fit), error = function(e) NULL)

  list(
    model_id = req$candidate_id,
    backend = "nlmixr2",
    converged = converged,
    ofv = ofv_val,
    aic = aic_val,
    bic = bic_val,
    parameter_estimates = param_list,
    eta_shrinkage = shrinkage,
    convergence_metadata = conv_meta,
    diagnostics = list(
      gof = gof,
      vpc = NULL,
      identifiability = list(
        condition_number = cond_num,
        profile_likelihood_ci = list(),
        ill_conditioned = !is.null(cond_num) && cond_num > 1e6
      ),
      blq = list(method = "none", lloq = NULL, n_blq = 0L, blq_fraction = 0.0),
      diagnostic_plots = list()
    ),
    wall_time_seconds = conv_meta$wall_time_seconds,
    backend_versions = list(
      nlmixr2 = as.character(packageVersion("nlmixr2")),
      R = paste0(R.version$major, ".", R.version$minor)
    ),
    initial_estimate_source = if (!is.null(req$initial_estimate_source))
                                req$initial_estimate_source else "fallback"
  )
}


# --- Main execution ---
# The compiled_r_code field contains R code generated by the DSL compiler
# (apmode.dsl.nlmixr2_emitter.emit_nlmixr2). It defines an nlmixr2 model
# function. This is trusted compiler output, not arbitrary user code.

tryCatch({
  # 1. Read request
  req <- fromJSON(request_path, simplifyVector = TRUE)

  # 2. Set RNG
  if (req$rng_kind == "L'Ecuyer-CMRG") {
    RNGkind("L'Ecuyer-CMRG")
  } else {
    RNGkind("Mersenne-Twister")
  }
  set.seed(req$seed)

  # 3. Load data
  data <- read.csv(req$data_path, header = TRUE, stringsAsFactors = FALSE)

  # 4. Build model function from DSL-compiled R code
  model_fn <- parse(text = req$compiled_r_code)
  model_fn <- base::eval(model_fn)

  # 5. Run estimation for each method, keep best by AIC
  estimation_methods <- req$estimation
  best_fit <- NULL
  best_method <- NULL

  for (method in estimation_methods) {
    fit <- tryCatch(
      nlmixr2(model_fn, data, est = method),
      error = function(e) {
        message(paste("APMODE: estimation method", method, "failed:", e$message))
        NULL
      }
    )
    if (!is.null(fit)) {
      fit_aic <- tryCatch(AIC(fit), error = function(e) Inf)
      best_aic <- if (!is.null(best_fit)) tryCatch(AIC(best_fit), error = function(e) Inf) else Inf
      if (fit_aic < best_aic) {
        best_fit <- fit
        best_method <- method
      }
    }
  }

  if (is.null(best_fit)) {
    # All estimation methods failed
    response <- list(
      schema_version = "1.0",
      status = "error",
      error_type = "convergence",
      result = NULL,
      r_session_info = .capture_session_info(),
      random_seed_state = as.integer(.Random.seed)
    )
  } else {
    # Extract results from best fit
    response <- list(
      schema_version = "1.0",
      status = "success",
      error_type = NULL,
      result = .extract_backend_result(best_fit, best_method, req),
      r_session_info = .capture_session_info(),
      random_seed_state = as.integer(.Random.seed)
    )
  }

  # 6. Write response
  write_json(response, response_path, auto_unbox = TRUE,
             null = "null", pretty = TRUE, digits = NA)

}, error = function(e) {
  # Crash-safe: write error response even on unexpected errors
  error_response <- list(
    schema_version = "1.0",
    status = "error",
    error_type = "crash",
    result = NULL,
    r_session_info = tryCatch(.capture_session_info(),
                               error = function(e2) {
                                 list(r_version = R.version.string,
                                      nlmixr2_version = "unknown",
                                      platform = .Platform$OS.type,
                                      packages = list())
                               }),
    random_seed_state = NULL
  )
  tryCatch(
    write_json(error_response, response_path, auto_unbox = TRUE,
               null = "null", pretty = TRUE),
    error = function(e3) {
      message(paste("APMODE: failed to write error response:", e3$message))
    }
  )
  quit(status = 1, save = "no")
})
