# SPDX-License-Identifier: GPL-2.0-or-later
# APMODE nlmixr2 estimation harness (ARCHITECTURE.md S4.2)
#
# Usage: Rscript harness.R <request.json> <response.json>
#
# Reads a typed request, runs nlmixr2 estimation, writes a typed response.
# All communication is file-based. stdout/stderr are for logging only.
#
# Security note: The R code evaluated here is generated by the APMODE DSL
# compiler (emit_nlmixr2), not user input. The DSL grammar constrains what
# can be expressed, and the semantic validator enforces safety invariants.

suppressPackageStartupMessages({
  library(jsonlite)
  library(nlmixr2)
  # rxode2 is a transitive dep of nlmixr2 and supplies rxSolve for
  # posterior-predictive simulation. Loaded explicitly so the
  # VPC helper does not rely on nlmixr2's re-exports.
  library(rxode2)
})

args <- commandArgs(trailingOnly = TRUE)
if (length(args) != 2) {
  stop("Usage: Rscript harness.R <request.json> <response.json>")
}

request_path <- args[1]
response_path <- args[2]

# --- Helper functions (defined before use) ---

.capture_session_info <- function() {
  nlmixr2_ver <- tryCatch(
    as.character(packageVersion("nlmixr2")),
    error = function(e) "unknown"
  )
  pkg_versions <- sapply(loadedNamespaces(), function(p) {
    tryCatch(as.character(packageVersion(p)), error = function(e) "unknown")
  })

  list(
    r_version = paste0(R.version$major, ".", R.version$minor),
    nlmixr2_version = nlmixr2_ver,
    platform = R.version$platform,
    packages = as.list(pkg_versions)
  )
}


.simulate_posterior_predictive <- function(fit, data, n_sims) {
  # Generate n_sims posterior-predictive replicates by sampling ETAs from
  # the fitted Omega (and residual noise from Sigma) and re-solving the
  # structural model at each subject's observed time points.
  #
  # Returns a list (one entry per subject) of:
  #   list(subject_id, t_observed, observed_dv, sims_at_observed)
  # where ``sims_at_observed`` is an n_sims x n_obs nested list (row = sim
  # replicate, col = observed time point), JSON-serializable.
  #
  # Returns NULL on any simulation error — the Python side treats NULL as
  # "backend did not emit sims" and falls back to the CWRES proxy for
  # Gate 3 ranking. Never raises, to keep the main harness path alive.
  if (is.null(n_sims) || n_sims <= 0) return(NULL)
  tryCatch({
    # rxode2 rejects ``keep`` containing reserved columns such as EVID and
    # typically DV — passing them aborts the whole call and returns NULL
    # here, silently killing the posterior-predictive pipeline. rxSolve
    # already drops dose-only rows from its output and the sim matrix
    # carries its own simulated DV column (``sim`` / ``cp``), so no pass-
    # through is needed; we read observed DV + observation times from the
    # original ``data`` frame below instead.
    sim_df <- rxode2::rxSolve(
      object = fit,
      events = data,
      nStud = as.integer(n_sims),
      returnType = "data.frame"
    )

    # Defensive filter in case a newer rxode2 starts surfacing EVID in the
    # output — keep the observation-only invariant downstream.
    if ("EVID" %in% names(sim_df)) {
      sim_df <- sim_df[sim_df$EVID == 0, , drop = FALSE]
    }

    # Identify the simulated DV column — rxode2 conventionally uses "sim",
    # but fits that carry a named endpoint sometimes use the DV variable.
    sim_col <- if ("sim" %in% names(sim_df)) "sim"
               else if ("cp" %in% names(sim_df)) "cp"
               else if ("DV.1" %in% names(sim_df)) "DV.1"
               else stop("could not identify simulated DV column in rxSolve output")

    sim_idx_col <- if ("sim.id" %in% names(sim_df)) "sim.id"
                   else if ("nSub" %in% names(sim_df)) "nSub"
                   else if ("nStud" %in% names(sim_df)) "nStud"
                   else stop("could not identify sim index column")

    data_obs <- data[data$EVID == 0, , drop = FALSE]
    subjects <- unique(as.character(data_obs$ID))

    # Per-subject sim matrices, still containing NA rows for failed sim
    # replicates. Sim-replicate failures are pruned globally after this
    # loop so every subject ends up with the same n_sims (the predictive
    # helper requires matching shapes across subjects).
    per_subj_mats <- vector("list", length(subjects))
    per_subj_meta <- vector("list", length(subjects))
    for (i in seq_along(subjects)) {
      sid <- subjects[i]
      subj_data <- data_obs[as.character(data_obs$ID) == sid, , drop = FALSE]
      # Order by TIME for stable AUC math downstream.
      subj_data <- subj_data[order(subj_data$TIME), , drop = FALSE]
      t_obs <- as.numeric(subj_data$TIME)
      dv_obs <- as.numeric(subj_data$DV)

      subj_sims <- sim_df[as.character(sim_df$id) == sid, , drop = FALSE]
      n_obs <- length(t_obs)
      mat <- matrix(NA_real_, nrow = n_sims, ncol = n_obs)
      for (s in seq_len(n_sims)) {
        s_rows <- subj_sims[subj_sims[[sim_idx_col]] == s, , drop = FALSE]
        s_rows <- s_rows[order(s_rows$time), , drop = FALSE]
        if (nrow(s_rows) == n_obs) {
          mat[s, ] <- as.numeric(s_rows[[sim_col]])
        }
      }
      per_subj_mats[[i]] <- mat
      per_subj_meta[[i]] <- list(subject_id = sid, t_observed = t_obs,
                                  observed_dv = dv_obs)
    }

    # Globally drop any sim replicate that has a non-finite entry for
    # ANY subject. rxode2 silently omits rows when its ODE solver fails
    # for an ETA draw; those rows surface here as all-NA. Keeping them
    # would poison jsonlite (``digits = NA`` serializes NA_real_ as the
    # string ``"NA"``, which blows up Pydantic downstream) AND violate
    # the matching-n_sims invariant in build_predictive_diagnostics.
    valid_sims <- rep(TRUE, n_sims)
    for (mat in per_subj_mats) {
      row_finite <- apply(mat, 1, function(r) all(is.finite(r)))
      valid_sims <- valid_sims & row_finite
    }
    n_valid <- sum(valid_sims)
    if (n_valid == 0L) {
      message(paste0("APMODE: VPC simulation produced zero valid ",
                     "replicates across subjects (requested ", n_sims,
                     "); falling back to CWRES proxy."))
      return(NULL)
    }
    if (n_valid < n_sims) {
      message(paste0("APMODE: VPC simulation dropped ", n_sims - n_valid,
                     " of ", n_sims, " sim replicates due to solver ",
                     "failures (kept ", n_valid, ")."))
    }

    out <- vector("list", length(subjects))
    for (i in seq_along(subjects)) {
      mat <- per_subj_mats[[i]][valid_sims, , drop = FALSE]
      sims_nested <- lapply(seq_len(nrow(mat)), function(r) as.numeric(mat[r, ]))
      out[[i]] <- c(per_subj_meta[[i]], list(sims_at_observed = sims_nested))
    }
    out
  }, error = function(e) {
    message(paste("APMODE: VPC simulation failed:", e$message))
    NULL
  })
}


.extract_backend_result <- function(fit, method, req) {
  # Parameter estimates from fixed effects table
  params <- as.data.frame(fit$parFixedDf)
  param_list <- list()

  has_se <- "SE" %in% names(params)
  has_rse <- "%RSE" %in% names(params)

  for (i in seq_len(nrow(params))) {
    pname <- rownames(params)[i]
    se_val <- if (has_se && !is.na(params$SE[i])) params$SE[i] else NULL
    rse_val <- if (has_rse && !is.na(params$`%RSE`[i])) params$`%RSE`[i] else NULL
    param_list[[pname]] <- list(
      name = pname,
      estimate = params$Estimate[i],
      se = se_val,
      rse = rse_val,
      ci95_lower = NULL,
      ci95_upper = NULL,
      fixed = FALSE,
      # Classify: eta.* -> iiv, sigma/prop/add -> residual, else structural
      category = if (grepl("^eta\\.", pname)) "iiv"
                 else if (grepl("prop|add|sigma", pname, ignore.case = TRUE)) "residual"
                 else "structural"
    )
  }

  # ETA shrinkage — nlmixr2 5.0 uses fit$shrink (data.frame) instead of
  # fit$shrinkage (named list). Extract SD shrinkage row for eta.* columns.
  shrinkage <- tryCatch({
    s <- fit$shrink
    if (is.data.frame(s) && "var" %in% rownames(s)) {
      # shrink df has rows: mean, var, sd, kurtosis, skewness
      # columns: eta.CL, eta.V, ... , IWRES
      eta_cols <- grep("^eta\\.", colnames(s), value = TRUE)
      vals <- as.list(s["var", eta_cols, drop = FALSE])
      # Rename eta.CL -> CL etc for downstream compatibility
      names(vals) <- sub("^eta\\.", "", names(vals))
      # Convert variance shrinkage to SD shrinkage fraction (0–1 scale).
      # SD shrinkage = 1 - sqrt(1 - var_shrinkage)
      # Gate policy threshold (shrinkage_max = 0.3) is also a fraction.
      lapply(vals, function(v) {
        if (is.numeric(v) && !is.na(v)) round(1 - sqrt(pmax(0, 1 - v)), 4)
        else NULL
      })
    } else if (!is.null(fit$shrinkage)) {
      as.list(fit$shrinkage)
    } else {
      list()
    }
  }, error = function(e) list())

  # Convergence info — check multiple indicators for robustness across
  # SAEM/FOCEI/nlme methods. In nlmixr2 5.0, fit$message may be empty
  # and fit$objDf$OBJF may be NA for SAEM. Use AIC(fit) as fallback.
  converged <- tryCatch({
    msg_ok <- !is.null(fit$message) && nchar(fit$message) > 0 &&
              grepl("successful|converge", fit$message, ignore.case = TRUE)
    # Check if OFV is finite
    ofv_ok <- tryCatch(!is.null(fit$objDf$OBJF[1]) && is.finite(fit$objDf$OBJF[1]),
                       error = function(e) FALSE)
    # Fallback: AIC is finite (nlmixr2 5.0 SAEM computes via Gaussian quadrature)
    aic_ok <- tryCatch(is.finite(AIC(fit)), error = function(e) FALSE)
    msg_ok || ofv_ok || aic_ok
  }, error = function(e) FALSE)

  # Wall time: nlmixr2 5.0 returns fit$time as data.frame, not named vector
  wall_secs <- tryCatch({
    t <- fit$time
    if (is.data.frame(t)) sum(as.numeric(unlist(t)), na.rm = TRUE)
    else as.numeric(t["elapsed"], units = "secs")
  }, error = function(e) 0.0)

  conv_meta <- list(
    method = method,
    converged = converged,
    iterations = if (!is.null(fit$niter)) as.integer(sum(fit$niter)) else 0L,
    gradient_norm = NULL,
    minimization_status = if (converged) "successful" else "terminated",
    wall_time_seconds = wall_secs
  )

  # GOF metrics — nlmixr2 5.0 SAEM may not compute CWRES by default;
  # fall back to IWRES (individual weighted residuals) which is always present
  gof <- tryCatch({
    wres <- if ("CWRES" %in% names(fit)) fit$CWRES else fit$IWRES
    if (is.null(wres) || length(wres) == 0) {
      list(cwres_mean = 0, cwres_sd = 1, outlier_fraction = 0, obs_vs_pred_r2 = NULL)
    } else {
      list(
        cwres_mean = mean(wres, na.rm = TRUE),
        cwres_sd = sd(wres, na.rm = TRUE),
        outlier_fraction = mean(abs(wres) > 4, na.rm = TRUE),
        obs_vs_pred_r2 = tryCatch(cor(fit$DV, fit$PRED, use = "complete.obs")^2,
                                   error = function(e) NULL)
      )
    }
  }, error = function(e) {
    list(cwres_mean = 0, cwres_sd = 1, outlier_fraction = 0, obs_vs_pred_r2 = NULL)
  })

  # Split GOF metrics — partition residuals by train/test if split manifest provided
  split_gof <- NULL
  if (!is.null(req$split_manifest) && length(req$split_manifest$assignments) > 0) {
    tryCatch({
      cwres <- if ("CWRES" %in% names(fit)) fit$CWRES else fit$IWRES
      if (is.null(cwres) || length(cwres) == 0) stop("no residuals available")
      fit_ids <- as.character(fit$ID)
      assignments <- req$split_manifest$assignments

      # Build subject→fold lookup
      fold_map <- setNames(
        sapply(assignments, function(a) a$fold),
        sapply(assignments, function(a) as.character(a$subject_id))
      )

      train_mask <- fit_ids %in% names(fold_map)[fold_map == "train"]
      test_mask  <- fit_ids %in% names(fold_map)[fold_map == "test"]

      if (sum(train_mask) > 0 && sum(test_mask) > 0) {
        split_gof <- list(
          train_cwres_mean = mean(cwres[train_mask], na.rm = TRUE),
          train_outlier_fraction = mean(abs(cwres[train_mask]) > 4, na.rm = TRUE),
          test_cwres_mean = mean(cwres[test_mask], na.rm = TRUE),
          test_outlier_fraction = mean(abs(cwres[test_mask]) > 4, na.rm = TRUE),
          n_train = as.integer(sum(train_mask)),
          n_test  = as.integer(sum(test_mask))
        )
      }
    }, error = function(e) {
      message(paste("APMODE: split_gof computation failed:", e$message))
    })
  }

  # Condition number — nlmixr2 5.0 renamed to conditionNumberCov/Cor
  cond_num <- tryCatch(fit$conditionNumberCov, error = function(e) {
    tryCatch(fit$conditionNumber, error = function(e2) NULL)
  })

  # OFV, AIC, BIC — nlmixr2 5.0 SAEM may have NA in objDf$OBJF;
  # AIC()/BIC() compute via Gaussian quadrature as fallback
  ofv_val <- tryCatch({
    v <- fit$objDf$OBJF[1]
    if (is.na(v)) NULL else v
  }, error = function(e) NULL)
  aic_val <- tryCatch(AIC(fit), error = function(e) NULL)
  bic_val <- tryCatch(BIC(fit), error = function(e) NULL)

  # Posterior-predictive simulation (VPC/NPE/AUC-Cmax source). Python
  # side derives VPC summary + npe_score + auc_cmax_be_score atomically
  # from this matrix via ``apmode.backends.predictive_summary.
  # build_predictive_diagnostics``. When n_posterior_predictive_sims is
  # 0 (default) or rxSolve fails, ``predicted_simulations`` is NULL and
  # the runner leaves the three diagnostics unset → Gate 3 falls back
  # to the CWRES proxy.
  #
  # When req$.test_data_frame is set (held-out NPE path), simulation
  # uses the held-out CSV instead of the training CSV — the fit object
  # supplies frozen THETA/OMEGA/SIGMA, rxode2 draws fresh ETAs from
  # Omega for the held-out subject IDs, and the resulting NPE measures
  # generalisation rather than goodness-of-fit. Subject IDs in the two
  # frames MUST be disjoint (subject-level k-fold split guarantees this
  # at the runner layer); a colliding ID would silently reuse the
  # train subject's posthoc ETA.
  n_sims <- if (!is.null(req$n_posterior_predictive_sims))
              as.integer(req$n_posterior_predictive_sims) else 0L
  sim_events <- if (!is.null(req$.test_data_frame)) req$.test_data_frame
                else req$.data_frame
  predicted_sims <- .simulate_posterior_predictive(fit, sim_events, n_sims)

  list(
    model_id = req$candidate_id,
    backend = "nlmixr2",
    converged = converged,
    ofv = ofv_val,
    aic = aic_val,
    bic = bic_val,
    parameter_estimates = param_list,
    eta_shrinkage = shrinkage,
    convergence_metadata = conv_meta,
    # ``diagnostics.vpc`` / ``npe_score`` / ``auc_cmax_be_score`` are
    # populated on the Python side via ``predicted_simulations`` below
    # — the single canonical path keeps VPC, NPE, and AUC/Cmax BE from
    # drifting apart across backends (see DiagnosticBundle docstring).
    diagnostics = list(
      gof = gof,
      split_gof = split_gof,
      vpc = NULL,
      identifiability = list(
        condition_number = cond_num,
        profile_likelihood_ci = setNames(list(), character(0)),
        ill_conditioned = !is.null(cond_num) && cond_num > 1e6
      ),
      blq = list(method = "none", lloq = NULL, n_blq = 0L, blq_fraction = 0.0),
      diagnostic_plots = setNames(list(), character(0))
    ),
    # Out-of-band carrier for build_predictive_diagnostics. Stays in the
    # raw dict (never validates into BackendResult) and is consumed by
    # Nlmixr2Runner._parse_response.
    predicted_simulations = predicted_sims,
    wall_time_seconds = wall_secs,
    backend_versions = list(
      nlmixr2 = as.character(packageVersion("nlmixr2")),
      R = paste0(R.version$major, ".", R.version$minor)
    ),
    initial_estimate_source = if (!is.null(req$initial_estimate_source))
                                req$initial_estimate_source else "fallback"
  )
}


# --- Main execution ---
# The compiled_r_code field contains R code generated by the DSL compiler
# (apmode.dsl.nlmixr2_emitter.emit_nlmixr2). It defines an nlmixr2 model
# function. This is trusted compiler output, not arbitrary user code.

tryCatch({
  # 1. Read request
  req <- fromJSON(request_path, simplifyVector = TRUE)

  # 2. Set RNG
  if (req$rng_kind == "L'Ecuyer-CMRG") {
    RNGkind("L'Ecuyer-CMRG")
  } else {
    RNGkind("Mersenne-Twister")
  }
  set.seed(req$seed)

  # 3. Load data.
  #
  # APMODE's canonical subject-id column is NMID; nlmixr2/rxode2 only
  # recognise the literal column name "ID" (case-insensitive). Without
  # the rename FOCEI silently treats every row as belonging to the same
  # subject, the residual likelihood becomes degenerate, and the outer
  # optimiser enters the Theta-reset (ETA drift) loop forever — which
  # surfaces as a per-fit BackendTimeoutError on small folds. The rename
  # is local to the R session: the persisted CSV keeps NMID so the bundle
  # / RO-Crate digest contracts and the per-fold train/test CSVs stay
  # byte-identical to the producer.
  .normalize_id_column <- function(df) {
    if (is.null(df)) return(df)
    if ("ID" %in% names(df)) return(df)
    if ("NMID" %in% names(df)) {
      names(df)[names(df) == "NMID"] <- "ID"
    }
    df
  }
  data <- read.csv(req$data_path, header = TRUE, stringsAsFactors = FALSE)
  data <- .normalize_id_column(data)
  # Stash on req for use inside .extract_backend_result (posterior-predictive
  # simulation needs the original event table). Keyed with a leading dot
  # so it can't collide with a schema field.
  req$.data_frame <- data

  # 3b. Optional held-out CSV. Read once and stash so the posterior-
  # predictive helper can route rxSolve at the held-out events. NULL or
  # empty => behaviour identical to today (in-sample sims).
  if (!is.null(req$test_data_path) && nzchar(req$test_data_path)) {
    req$.test_data_frame <- .normalize_id_column(
      read.csv(req$test_data_path, header = TRUE, stringsAsFactors = FALSE)
    )
  }

  # 4. Build model function from DSL-compiled R code
  model_fn <- parse(text = req$compiled_r_code)
  model_fn <- base::eval(model_fn)

  # 5. Run estimation for each method, keep best by AIC.
  # When fixed_parameter is set, override with a single posthoc pass
  # so nlmixr2 freezes THETA/OMEGA/SIGMA at the compiled ini() values
  # and only fits ETAs. The AIC-best loop collapses to a single method
  # by construction; downstream extract still picks the (only) survivor.
  estimation_methods <- if (isTRUE(req$fixed_parameter)) {
    c("posthoc")
  } else {
    req$estimation
  }
  best_fit <- NULL
  best_method <- NULL

  for (method in estimation_methods) {
    fit <- tryCatch(
      nlmixr2(model_fn, data, est = method),
      error = function(e) {
        message(paste("APMODE: estimation method", method, "failed:", e$message))
        NULL
      }
    )
    if (!is.null(fit)) {
      fit_aic <- tryCatch(AIC(fit), error = function(e) Inf)
      best_aic <- if (!is.null(best_fit)) tryCatch(AIC(best_fit), error = function(e) Inf) else Inf
      if (fit_aic < best_aic) {
        best_fit <- fit
        best_method <- method
      }
    }
  }

  if (is.null(best_fit)) {
    # All estimation methods failed
    response <- list(
      schema_version = "1.0",
      status = "error",
      error_type = "convergence",
      result = NULL,
      r_session_info = .capture_session_info(),
      random_seed_state = as.integer(.Random.seed)
    )
  } else {
    # Extract results from best fit
    response <- list(
      schema_version = "1.0",
      status = "success",
      error_type = NULL,
      result = .extract_backend_result(best_fit, best_method, req),
      r_session_info = .capture_session_info(),
      random_seed_state = as.integer(.Random.seed)
    )
  }

  # 6. Write response. ``na = "null"`` is load-bearing: with ``digits =
  # NA`` jsonlite's default format path serializes ``NA_real_`` as the
  # string ``"NA"`` rather than JSON null, which blows up Pydantic's
  # float parsing on the Python side. We also prune NA sim rows upstream
  # in .simulate_posterior_predictive, but keep this as the last line of
  # defense for any NA that escapes from fit-summary fields (shrinkage,
  # %RSE, etc.).
  write_json(response, response_path, auto_unbox = TRUE,
             null = "null", na = "null", pretty = TRUE, digits = NA)

}, error = function(e) {
  # Crash-safe: write error response even on unexpected errors
  error_response <- list(
    schema_version = "1.0",
    status = "error",
    error_type = "crash",
    result = NULL,
    r_session_info = tryCatch(.capture_session_info(),
                               error = function(e2) {
                                 list(r_version = R.version.string,
                                      nlmixr2_version = "unknown",
                                      platform = .Platform$OS.type,
                                      packages = list())
                               }),
    random_seed_state = NULL
  )
  tryCatch(
    write_json(error_response, response_path, auto_unbox = TRUE,
               null = "null", na = "null", pretty = TRUE),
    error = function(e3) {
      message(paste("APMODE: failed to write error response:", e3$message))
    }
  )
  quit(status = 1, save = "no")
})
