# SPDX-License-Identifier: GPL-2.0-or-later
# APMODE nlmixr2 estimation harness (ARCHITECTURE.md S4.2)
#
# Usage: Rscript harness.R <request.json> <response.json>
#
# Reads a typed request, runs nlmixr2 estimation, writes a typed response.
# All communication is file-based. stdout/stderr are for logging only.
#
# Security note: The R code evaluated here is generated by the APMODE DSL
# compiler (emit_nlmixr2), not user input. The DSL grammar constrains what
# can be expressed, and the semantic validator enforces safety invariants.

suppressPackageStartupMessages({
  library(jsonlite)
  library(nlmixr2)
})

args <- commandArgs(trailingOnly = TRUE)
if (length(args) != 2) {
  stop("Usage: Rscript harness.R <request.json> <response.json>")
}

request_path <- args[1]
response_path <- args[2]

# --- Helper functions (defined before use) ---

.capture_session_info <- function() {
  nlmixr2_ver <- tryCatch(
    as.character(packageVersion("nlmixr2")),
    error = function(e) "unknown"
  )
  pkg_versions <- sapply(loadedNamespaces(), function(p) {
    tryCatch(as.character(packageVersion(p)), error = function(e) "unknown")
  })

  list(
    r_version = paste0(R.version$major, ".", R.version$minor),
    nlmixr2_version = nlmixr2_ver,
    platform = R.version$platform,
    packages = as.list(pkg_versions)
  )
}


.extract_backend_result <- function(fit, method, req) {
  # Parameter estimates from fixed effects table
  params <- as.data.frame(fit$parFixedDf)
  param_list <- list()

  has_se <- "SE" %in% names(params)
  has_rse <- "%RSE" %in% names(params)

  for (i in seq_len(nrow(params))) {
    pname <- rownames(params)[i]
    se_val <- if (has_se && !is.na(params$SE[i])) params$SE[i] else NULL
    rse_val <- if (has_rse && !is.na(params$`%RSE`[i])) params$`%RSE`[i] else NULL
    param_list[[pname]] <- list(
      name = pname,
      estimate = params$Estimate[i],
      se = se_val,
      rse = rse_val,
      ci95_lower = NULL,
      ci95_upper = NULL,
      fixed = FALSE,
      # Classify: eta.* -> iiv, sigma/prop/add -> residual, else structural
      category = if (grepl("^eta\\.", pname)) "iiv"
                 else if (grepl("prop|add|sigma", pname, ignore.case = TRUE)) "residual"
                 else "structural"
    )
  }

  # ETA shrinkage — nlmixr2 5.0 uses fit$shrink (data.frame) instead of
  # fit$shrinkage (named list). Extract SD shrinkage row for eta.* columns.
  shrinkage <- tryCatch({
    s <- fit$shrink
    if (is.data.frame(s) && "var" %in% rownames(s)) {
      # shrink df has rows: mean, var, sd, kurtosis, skewness
      # columns: eta.CL, eta.V, ... , IWRES
      eta_cols <- grep("^eta\\.", colnames(s), value = TRUE)
      vals <- as.list(s["var", eta_cols, drop = FALSE])
      # Rename eta.CL -> CL etc for downstream compatibility
      names(vals) <- sub("^eta\\.", "", names(vals))
      # Convert variance shrinkage to SD shrinkage percentage
      # SD shrinkage = (1 - sqrt(1 - var_shrinkage)) * 100
      lapply(vals, function(v) {
        if (is.numeric(v) && !is.na(v)) round((1 - sqrt(pmax(0, 1 - v))) * 100, 2)
        else NULL
      })
    } else if (!is.null(fit$shrinkage)) {
      as.list(fit$shrinkage)
    } else {
      list()
    }
  }, error = function(e) list())

  # Convergence info — check multiple indicators for robustness across
  # SAEM/FOCEI/nlme methods. In nlmixr2 5.0, fit$message may be empty
  # and fit$objDf$OBJF may be NA for SAEM. Use AIC(fit) as fallback.
  converged <- tryCatch({
    msg_ok <- !is.null(fit$message) && nchar(fit$message) > 0 &&
              grepl("successful|converge", fit$message, ignore.case = TRUE)
    # Check if OFV is finite
    ofv_ok <- tryCatch(!is.null(fit$objDf$OBJF[1]) && is.finite(fit$objDf$OBJF[1]),
                       error = function(e) FALSE)
    # Fallback: AIC is finite (nlmixr2 5.0 SAEM computes via Gaussian quadrature)
    aic_ok <- tryCatch(is.finite(AIC(fit)), error = function(e) FALSE)
    msg_ok || ofv_ok || aic_ok
  }, error = function(e) FALSE)

  # Wall time: nlmixr2 5.0 returns fit$time as data.frame, not named vector
  wall_secs <- tryCatch({
    t <- fit$time
    if (is.data.frame(t)) sum(as.numeric(unlist(t)), na.rm = TRUE)
    else as.numeric(t["elapsed"], units = "secs")
  }, error = function(e) 0.0)

  conv_meta <- list(
    method = method,
    converged = converged,
    iterations = if (!is.null(fit$niter)) as.integer(sum(fit$niter)) else 0L,
    gradient_norm = NULL,
    minimization_status = if (converged) "successful" else "terminated",
    wall_time_seconds = wall_secs
  )

  # GOF metrics — nlmixr2 5.0 SAEM may not compute CWRES by default;
  # fall back to IWRES (individual weighted residuals) which is always present
  gof <- tryCatch({
    wres <- if ("CWRES" %in% names(fit)) fit$CWRES else fit$IWRES
    if (is.null(wres) || length(wres) == 0) {
      list(cwres_mean = 0, cwres_sd = 1, outlier_fraction = 0, obs_vs_pred_r2 = NULL)
    } else {
      list(
        cwres_mean = mean(wres, na.rm = TRUE),
        cwres_sd = sd(wres, na.rm = TRUE),
        outlier_fraction = mean(abs(wres) > 4, na.rm = TRUE),
        obs_vs_pred_r2 = tryCatch(cor(fit$DV, fit$PRED, use = "complete.obs")^2,
                                   error = function(e) NULL)
      )
    }
  }, error = function(e) {
    list(cwres_mean = 0, cwres_sd = 1, outlier_fraction = 0, obs_vs_pred_r2 = NULL)
  })

  # Split GOF metrics — partition residuals by train/test if split manifest provided
  split_gof <- NULL
  if (!is.null(req$split_manifest) && length(req$split_manifest$assignments) > 0) {
    tryCatch({
      cwres <- if ("CWRES" %in% names(fit)) fit$CWRES else fit$IWRES
      if (is.null(cwres) || length(cwres) == 0) stop("no residuals available")
      fit_ids <- as.character(fit$ID)
      assignments <- req$split_manifest$assignments

      # Build subject→fold lookup
      fold_map <- setNames(
        sapply(assignments, function(a) a$fold),
        sapply(assignments, function(a) as.character(a$subject_id))
      )

      train_mask <- fit_ids %in% names(fold_map)[fold_map == "train"]
      test_mask  <- fit_ids %in% names(fold_map)[fold_map == "test"]

      if (sum(train_mask) > 0 && sum(test_mask) > 0) {
        split_gof <- list(
          train_cwres_mean = mean(cwres[train_mask], na.rm = TRUE),
          train_outlier_fraction = mean(abs(cwres[train_mask]) > 4, na.rm = TRUE),
          test_cwres_mean = mean(cwres[test_mask], na.rm = TRUE),
          test_outlier_fraction = mean(abs(cwres[test_mask]) > 4, na.rm = TRUE),
          n_train = as.integer(sum(train_mask)),
          n_test  = as.integer(sum(test_mask))
        )
      }
    }, error = function(e) {
      message(paste("APMODE: split_gof computation failed:", e$message))
    })
  }

  # Condition number — nlmixr2 5.0 renamed to conditionNumberCov/Cor
  cond_num <- tryCatch(fit$conditionNumberCov, error = function(e) {
    tryCatch(fit$conditionNumber, error = function(e2) NULL)
  })

  # OFV, AIC, BIC — nlmixr2 5.0 SAEM may have NA in objDf$OBJF;
  # AIC()/BIC() compute via Gaussian quadrature as fallback
  ofv_val <- tryCatch({
    v <- fit$objDf$OBJF[1]
    if (is.na(v)) NULL else v
  }, error = function(e) NULL)
  aic_val <- tryCatch(AIC(fit), error = function(e) NULL)
  bic_val <- tryCatch(BIC(fit), error = function(e) NULL)

  list(
    model_id = req$candidate_id,
    backend = "nlmixr2",
    converged = converged,
    ofv = ofv_val,
    aic = aic_val,
    bic = bic_val,
    parameter_estimates = param_list,
    eta_shrinkage = shrinkage,
    convergence_metadata = conv_meta,
    diagnostics = list(
      gof = gof,
      split_gof = split_gof,
      vpc = NULL,
      identifiability = list(
        condition_number = cond_num,
        profile_likelihood_ci = setNames(list(), character(0)),
        ill_conditioned = !is.null(cond_num) && cond_num > 1e6
      ),
      blq = list(method = "none", lloq = NULL, n_blq = 0L, blq_fraction = 0.0),
      diagnostic_plots = setNames(list(), character(0))
    ),
    wall_time_seconds = wall_secs,
    backend_versions = list(
      nlmixr2 = as.character(packageVersion("nlmixr2")),
      R = paste0(R.version$major, ".", R.version$minor)
    ),
    initial_estimate_source = if (!is.null(req$initial_estimate_source))
                                req$initial_estimate_source else "fallback"
  )
}


# --- Main execution ---
# The compiled_r_code field contains R code generated by the DSL compiler
# (apmode.dsl.nlmixr2_emitter.emit_nlmixr2). It defines an nlmixr2 model
# function. This is trusted compiler output, not arbitrary user code.

tryCatch({
  # 1. Read request
  req <- fromJSON(request_path, simplifyVector = TRUE)

  # 2. Set RNG
  if (req$rng_kind == "L'Ecuyer-CMRG") {
    RNGkind("L'Ecuyer-CMRG")
  } else {
    RNGkind("Mersenne-Twister")
  }
  set.seed(req$seed)

  # 3. Load data
  data <- read.csv(req$data_path, header = TRUE, stringsAsFactors = FALSE)

  # 4. Build model function from DSL-compiled R code
  model_fn <- parse(text = req$compiled_r_code)
  model_fn <- base::eval(model_fn)

  # 5. Run estimation for each method, keep best by AIC
  estimation_methods <- req$estimation
  best_fit <- NULL
  best_method <- NULL

  for (method in estimation_methods) {
    fit <- tryCatch(
      nlmixr2(model_fn, data, est = method),
      error = function(e) {
        message(paste("APMODE: estimation method", method, "failed:", e$message))
        NULL
      }
    )
    if (!is.null(fit)) {
      fit_aic <- tryCatch(AIC(fit), error = function(e) Inf)
      best_aic <- if (!is.null(best_fit)) tryCatch(AIC(best_fit), error = function(e) Inf) else Inf
      if (fit_aic < best_aic) {
        best_fit <- fit
        best_method <- method
      }
    }
  }

  if (is.null(best_fit)) {
    # All estimation methods failed
    response <- list(
      schema_version = "1.0",
      status = "error",
      error_type = "convergence",
      result = NULL,
      r_session_info = .capture_session_info(),
      random_seed_state = as.integer(.Random.seed)
    )
  } else {
    # Extract results from best fit
    response <- list(
      schema_version = "1.0",
      status = "success",
      error_type = NULL,
      result = .extract_backend_result(best_fit, best_method, req),
      r_session_info = .capture_session_info(),
      random_seed_state = as.integer(.Random.seed)
    )
  }

  # 6. Write response
  write_json(response, response_path, auto_unbox = TRUE,
             null = "null", pretty = TRUE, digits = NA)

}, error = function(e) {
  # Crash-safe: write error response even on unexpected errors
  error_response <- list(
    schema_version = "1.0",
    status = "error",
    error_type = "crash",
    result = NULL,
    r_session_info = tryCatch(.capture_session_info(),
                               error = function(e2) {
                                 list(r_version = R.version.string,
                                      nlmixr2_version = "unknown",
                                      platform = .Platform$OS.type,
                                      packages = list())
                               }),
    random_seed_state = NULL
  )
  tryCatch(
    write_json(error_response, response_path, auto_unbox = TRUE,
               null = "null", pretty = TRUE),
    error = function(e3) {
      message(paste("APMODE: failed to write error response:", e3$message))
    }
  )
  quit(status = 1, save = "no")
})
