# SPDX-License-Identifier: GPL-2.0-or-later
"""Bundle emitter (ARCHITECTURE.md §5, PRD §4.3.2).

Writes all reproducibility bundle artifacts to disk. Each JSON/JSONL artifact
is Pydantic-validated before writing (enforced by typed method signatures).

Artifacts:
  data_manifest.json, seed_registry.json, backend_versions.json, policy_file.json,
  evidence_manifest.json, initial_estimates.json, split_manifest.json,
  search_trajectory.jsonl, failed_candidates.jsonl, candidate_lineage.json,
  compiled_specs/{id}.json + .R, results/{id}_result.json,
  gate_decisions/gate{n}_{id}.json
"""

from __future__ import annotations

import contextlib
import hashlib
import json
import os
import re
import threading
from pathlib import Path  # noqa: TC003 — used at runtime in __init__
from typing import Any, Literal

from apmode.bundle.models import (
    AgenticTraceInput,
    AgenticTraceMeta,
    AgenticTraceOutput,
    BackendResult,
    BackendVersions,
    CandidateLineage,
    CategoricalEncodingProvenance,
    CredibilityReport,
    DataManifest,
    EvidenceManifest,
    FailedCandidate,
    GateResult,
    ImputationStabilityManifest,
    InitialEstimates,
    LOOSummary,
    LOROCVResult,
    MissingDataDirective,
    NCASubjectDiagnostic,
    PosteriorDiagnostics,
    PriorDataConflict,
    PriorManifest,
    PriorManifestEntry,
    PriorSensitivity,
    Ranking,
    ReparameterizationRecommendation,
    ReportProvenance,
    RunLineage,
    SamplerConfig,
    SBCManifest,
    SearchGraph,
    SearchTrajectoryEntry,
    SeedRegistry,
    SimulationProtocol,
    SplitManifest,
)
from apmode.dsl.ast_models import DSLSpec  # noqa: TC001 — used at runtime
from apmode.dsl.nlmixr2_emitter import emit_nlmixr2
from apmode.dsl.priors import (
    PriorSpec,
    validate_prior_justification,
)
from apmode.ids import generate_run_id

_SAFE_ID_RE = re.compile(r"^[a-zA-Z0-9_\-]+$")

# Sentinel file emitted by :meth:`BundleEmitter.seal` to mark a bundle as
# complete. Its contents carry a SHA-256 digest of every other file in the
# bundle, letting downstream tooling detect both incompleteness (absence of
# the sentinel) and post-hoc tampering (digest mismatch).
_COMPLETE_SENTINEL = "_COMPLETE"
# Producer-side sidecar filename for the CycloneDX SBOM. Emitted by
# ``apmode bundle sbom`` (and CI) as a post-seal provenance artifact.
# Excluded from the sealed-bundle digest so that generating or
# regenerating the SBOM does not invalidate ``_COMPLETE``.
_SBOM_FILENAME = "bom.cdx.json"
# SBC manifest is regenerated by the nightly runner (plan Task 27); the
# producer-side stub lives at ``artifacts/sbc/sbc_manifest.json``.
# Excluded from the sealed digest so a nightly rewrite does not invalidate
# ``_COMPLETE`` (same logic as the SBOM sidecar). Stored as the
# bundle-relative path because the digest exclusion compares against
# the relative path rather than the basename — so a same-named
# artefact in another subdir is *not* exempted.
_SBC_MANIFEST_FILENAME = "sbc_manifest.json"
_SBC_MANIFEST_RELPATH = "artifacts/sbc/sbc_manifest.json"
# The seal step writes ``_COMPLETE.tmp`` first and atomically renames it
# to ``_COMPLETE``; including the temp file in the digest would taint
# bundles whose seal happened to be retried after a partial rename, so
# it joins the exclusion set alongside the sidecars.
_COMPLETE_SENTINEL_TMP = _COMPLETE_SENTINEL + ".tmp"
# Bundle-relative POSIX paths excluded from the sealed-bundle digest.
# Compared against ``p.relative_to(run_dir).as_posix()`` rather than
# basename so a future backend that emits a same-named artefact under
# ``compiled_specs/<id>/bom.cdx.json`` is not silently exempted from
# the seal. Kept private — the importer at
# ``apmode.bundle.rocrate.importer`` carries its own copy to avoid a
# heavyweight import dependency.
_DIGEST_EXCLUDED_RELATIVE_PATHS: frozenset[str] = frozenset(
    {
        _COMPLETE_SENTINEL,
        _COMPLETE_SENTINEL_TMP,
        # SBOM sidecar lives at the bundle root, so its relative path
        # is just the basename.
        _SBOM_FILENAME,
        # SBC manifest lives in a nested ``artifacts/sbc/`` subdir;
        # the relative path makes the exclusion specific so a future
        # ``compiled_specs/<id>/sbc_manifest.json`` would *not* be
        # silently exempted.
        _SBC_MANIFEST_RELPATH,
    }
)
_HASH_CHUNK_SIZE = 1024 * 1024
# Module-level lock that serialises ``_compute_bundle_digest`` against
# any concurrent caller of ``BundleEmitter.append_*`` on the same run
# directory. The asyncio-only invariant in production already prevents
# concurrent mutation, but the lock turns the latent TOCTOU window —
# between ``rglob`` listing the files and ``read_bytes()`` consuming
# each one — into a structural guard that survives any future caller
# offloading writes to ``asyncio.to_thread``.
#
# ``RLock`` is required (not plain ``Lock``) because ``BundleEmitter.seal``
# acquires the lock and then calls ``_compute_bundle_digest`` which
# acquires it again on the same thread. A non-reentrant lock would
# deadlock every successful run at the seal step.
_DIGEST_LOCK = threading.RLock()
# Schema v2 (v0.5.0): adds per-candidate ``scoring_contract`` on
# :class:`~apmode.bundle.models.DiagnosticBundle`. Bundles produced before
# this version do not carry the field; they can be migrated at read time by
# injecting the nlmixr2-default contract (``re_treatment="integrated"``,
# ``nlpd_integrator="nlmixr2_focei"``, ``float_precision="float64"``).
_COMPLETE_SCHEMA_VERSION = 2


class BundleAlreadySealedError(RuntimeError):
    """Raised when an attempt is made to modify a sealed bundle."""


def _prior_family_hyperparams(
    spec: PriorSpec,
) -> dict[str, float | list[float] | str | list[str]]:
    """Flatten a ``PriorFamily`` into the ``PriorManifestEntry.hyperparams`` shape.

    Mixture components — which are themselves Pydantic models — are
    serialised as a ``list[str]`` of compact JSON so the hyperparams field
    can stay primitive-typed on disk. Numeric fields are coerced to ``float``
    (no silent int→float drift). The only keys that can appear are those
    declared on the specific ``PriorFamily`` variant, plus Mixture's
    ``components``/``weights`` pair and HistoricalBorrowing's string
    ``historical_refs``.
    """
    dump = spec.family.model_dump(mode="python")
    dump.pop("type", None)
    flat: dict[str, float | list[float] | str | list[str]] = {}
    for key, value in dump.items():
        # ``bool`` is a subclass of ``int`` — the union also catches it, but
        # we coerce everything through ``float()`` so the narrower arm is
        # not meaningful behaviourally; one branch keeps the intent clear.
        if isinstance(value, bool | int | float):
            flat[key] = float(value)
        elif isinstance(value, str):
            flat[key] = value
        elif isinstance(value, list):
            if not value:
                flat[key] = []
            elif all(isinstance(x, int | float) and not isinstance(x, bool) for x in value):
                flat[key] = [float(x) for x in value]
            elif all(isinstance(x, str) for x in value):
                flat[key] = list(value)
            else:
                flat[key] = [json.dumps(x, sort_keys=True, default=str) for x in value]
        else:
            flat[key] = json.dumps(value, sort_keys=True, default=str)
    return flat


def _prior_spec_to_manifest_entry(spec: PriorSpec) -> PriorManifestEntry:
    """Project a DSL ``PriorSpec`` onto a bundle-side ``PriorManifestEntry``."""
    return PriorManifestEntry(
        target=spec.target,
        family=spec.family.type,
        source=spec.source,
        hyperparams=_prior_family_hyperparams(spec),
        justification=spec.justification,
        historical_refs=list(spec.historical_refs),
        doi=spec.doi,
    )


def build_prior_manifest(
    specs: list[PriorSpec],
    *,
    policy_version: str,
    default_prior_policy: Literal["weakly_informative", "custom"] = "weakly_informative",
    justification_min_length: int = 50,
) -> PriorManifest:
    """Validate a list of ``PriorSpec``s and build the on-disk manifest.

    Every informative spec (``historical_data`` / ``expert_elicitation`` /
    ``meta_analysis``) is run through
    :func:`apmode.dsl.priors.validate_prior_justification` with the
    caller-supplied ``justification_min_length``. Errors from every spec
    are collected before raising so reviewers see every failing prior in
    one pass rather than one-at-a-time.

    Args:
        specs: DSL-side prior declarations (typically ``DSLSpec.priors``).
        policy_version: The lane policy version in force at emit time.
            Recorded verbatim on the manifest so re-validation can check
            the same threshold set.
        default_prior_policy: Whether unspecified parameters fall back to
            weakly-informative defaults or a custom recipe.
        justification_min_length: Minimum justification length to enforce.
            Defaults to the FDA Gate 2 floor (50 chars); lane policies may
            tighten this (e.g. submission lane bumps to 500 — Task 19).

    Raises:
        ValueError: Aggregated justification/DOI errors from every spec
            that failed validation. The message includes one line per
            error, prefixed with ``priors[i] (target=...)``.
    """
    errors: list[str] = []
    for idx, spec in enumerate(specs):
        for msg in validate_prior_justification(spec, min_length=justification_min_length):
            errors.append(f"priors[{idx}] (target={spec.target!r}): {msg}")
    if errors:
        raise ValueError("prior_manifest validation failed:\n  " + "\n  ".join(errors))
    return PriorManifest(
        policy_version=policy_version,
        entries=[_prior_spec_to_manifest_entry(s) for s in specs],
        default_prior_policy=default_prior_policy,
    )


def _validate_path_component(value: str, label: str) -> None:
    """Reject IDs containing path traversal characters."""
    if not _SAFE_ID_RE.match(value):
        msg = f"{label} contains unsafe characters: {value!r}"
        raise ValueError(msg)


def _atomic_durable_write(tmp_path: Path, text: str) -> None:
    """Write ``text`` to ``tmp_path`` and fsync the file before returning.

    Used as the producer side of the tmp-file-then-``os.replace`` dance.
    Going through ``os.open`` + ``os.fsync`` (rather than
    ``Path.write_text``) makes the data durability explicit — without
    the fsync, a SIGKILL between the write returning and the rename
    can leave the renamed file with stale page-cache contents on
    filesystems that do not auto-flush data before a metadata commit.
    """
    fd = os.open(tmp_path, os.O_WRONLY | os.O_CREAT | os.O_TRUNC, 0o644)
    try:
        os.write(fd, text.encode("utf-8"))
        os.fsync(fd)
    finally:
        os.close(fd)


def _fsync_dir(directory: Path) -> None:
    """Fsync the directory entry so a fresh ``os.replace`` survives a crash.

    POSIX requires the directory itself to be fsynced before its
    rename is durable. Best-effort: the operation is a no-op on
    platforms (Windows) that do not let us open a directory for fsync,
    and ``OSError`` is swallowed so the call site does not have to
    distinguish "fsync unsupported" from real I/O failure (the
    earlier ``os.fsync`` on the file fd already covers the most
    common durability gap).
    """
    try:
        fd = os.open(directory, os.O_RDONLY)
    except OSError:
        return
    try:
        with contextlib.suppress(OSError):
            os.fsync(fd)
    finally:
        os.close(fd)


def _compute_bundle_digest(run_dir: Path) -> str:
    """Compute a stable SHA-256 digest over all files in ``run_dir``.

    The sentinel file (and its ``.tmp`` mid-write twin) plus the SBOM /
    SBC sidecars are excluded. Files are hashed in sorted order by
    POSIX-relative path, with path + null byte + bytes, so the digest is
    reproducible across filesystems that differ in readdir order.

    The process-wide lock serialises digesting against all emitter-owned
    writes. File payloads are streamed in chunks rather than materialised
    wholesale, so large posterior artifacts do not create a second in-memory
    copy during sealing.
    """
    with _DIGEST_LOCK:
        digest = hashlib.sha256()
        for p in sorted(run_dir.rglob("*"), key=lambda q: q.relative_to(run_dir).as_posix()):
            if not p.is_file():
                continue
            rel = p.relative_to(run_dir).as_posix()
            # Match exclusions on the bundle-relative path so a same-named
            # artefact in a nested subdir is *not* silently exempted from
            # the digest. Top-level sentinels (``_COMPLETE``,
            # ``bom.cdx.json``, ...) sit at the bundle root, so their
            # relative path equals the bare filename.
            if rel in _DIGEST_EXCLUDED_RELATIVE_PATHS:
                continue
            digest.update(rel.encode("utf-8"))
            digest.update(b"\0")
            with p.open("rb") as f:
                for chunk in iter(lambda: f.read(_HASH_CHUNK_SIZE), b""):
                    digest.update(chunk)
        return digest.hexdigest()


class BundleEmitter:
    """Writes reproducibility bundle artifacts to disk.

    All artifacts per ARCHITECTURE.md §5 / PRD §4.3.2:
    - data_manifest.json, seed_registry.json, backend_versions.json
    - evidence_manifest.json, initial_estimates.json, split_manifest.json
    - policy_file.json
    - compiled_specs/{candidate_id}.json + .R
    - results/{candidate_id}_result.json
    - gate_decisions/gate{n}_{candidate_id}.json
    - search_trajectory.jsonl, failed_candidates.jsonl, candidate_lineage.json
    """

    def __init__(self, base_dir: Path, run_id: str | None = None) -> None:
        self.run_id = run_id or generate_run_id()
        self.run_dir = base_dir / self.run_id
        self._compiled_specs_dir = self.run_dir / "compiled_specs"
        self._gate_decisions_dir = self.run_dir / "gate_decisions"
        self._results_dir = self.run_dir / "results"

    def initialize(self) -> Path:
        """Create the bundle directory structure. Returns the run directory.

        Refuses to modify a bundle that has already been sealed (contains the
        ``_COMPLETE`` sentinel). Orchestrators must use a fresh run_id to
        re-run; this protects sealed artifacts from accidental mutation.
        """
        self.run_dir.mkdir(parents=True, exist_ok=True)
        if (self.run_dir / _COMPLETE_SENTINEL).exists():
            msg = f"bundle {self.run_dir} is sealed; refusing to reopen (use a fresh run_id)"
            raise BundleAlreadySealedError(msg)
        self._compiled_specs_dir.mkdir(exist_ok=True)
        self._gate_decisions_dir.mkdir(exist_ok=True)
        self._results_dir.mkdir(exist_ok=True)
        return self.run_dir

    def seal(self) -> Path:
        """Atomically seal the bundle by writing the ``_COMPLETE`` sentinel.

        The sentinel is a JSON document carrying a SHA-256 digest of every
        other file in the bundle, the schema version, and the run_id. It
        must be written as the LAST step of a successful run; its presence
        is what ``apmode validate`` uses to distinguish complete from
        partial bundles (PRD §4.3.2).

        Idempotent: calling on an already-sealed bundle returns the path
        without rewriting. The whole digest-then-rename sequence runs
        under the module-level ``_DIGEST_LOCK`` so any concurrent
        ``append_*`` that races with the seal is serialised and either
        lands strictly before the snapshot or is rejected by the
        ``is_sealed()`` guard *after* the rename.
        """
        sentinel_path = self.run_dir / _COMPLETE_SENTINEL
        if sentinel_path.exists():
            return self.run_dir

        with _DIGEST_LOCK:
            if sentinel_path.exists():  # pragma: no cover - racy double-call
                return self.run_dir
            sentinel = {
                "schema_version": _COMPLETE_SCHEMA_VERSION,
                "run_id": self.run_id,
                "sha256": _compute_bundle_digest(self.run_dir),
            }
            # #32 / #34: write the sentinel through a tmp + os.replace
            # dance so a mid-write crash (SIGKILL, OOM) cannot leave a
            # partially written _COMPLETE that a subsequent
            # ``initialize()`` would treat as a valid seal. The
            # tmp-file is fsynced *before* the rename and the parent
            # directory is fsynced *after* so the integrity anchor is
            # durable across power loss and not just process death.
            # ``os.replace`` is atomic on the same filesystem on both
            # POSIX and Windows; the tmp file is cleaned up before the
            # rename so there is no orphan file after a successful call.
            tmp_path = sentinel_path.with_suffix(".tmp")
            _atomic_durable_write(tmp_path, json.dumps(sentinel, indent=2) + "\n")
            os.replace(tmp_path, sentinel_path)
            _fsync_dir(self.run_dir)
        return self.run_dir

    def is_sealed(self) -> bool:
        """Return True when the ``_COMPLETE`` sentinel is present."""
        return (self.run_dir / _COMPLETE_SENTINEL).exists()

    def _ensure_unsealed(self) -> None:
        if self.is_sealed():
            msg = f"bundle {self.run_dir} is sealed; refusing to modify artifacts"
            raise BundleAlreadySealedError(msg)

    def _write_text(self, path: Path, text: str, *, allow_sealed: bool = False) -> Path:
        """Atomically write text while preserving the sealed-bundle invariant.

        ``Path.write_text`` returns once the bytes land in the OS page
        cache; on filesystems that reorder data and metadata writes
        (NFS, overlayfs, ext4 without ``auto_da_alloc``) a SIGKILL/OOM
        between the write returning and ``os.replace`` can leave a
        successfully-renamed file with stale or zeroed contents. We
        therefore fsync the file *and* its parent directory before the
        rename so a crashed seal cannot resurrect a phantom artefact.
        Linux ext4 with the standard ``auto_da_alloc`` heuristic
        already approximates this; we make the durability contract
        explicit so it survives an admin disabling the heuristic or
        the bundle living on a network filesystem.
        """
        with _DIGEST_LOCK:
            if not allow_sealed:
                self._ensure_unsealed()
            path.parent.mkdir(parents=True, exist_ok=True)
            tmp_path = path.with_name(f".{path.name}.{os.getpid()}.{threading.get_ident()}.tmp")
            try:
                _atomic_durable_write(tmp_path, text)
                os.replace(tmp_path, path)
                _fsync_dir(path.parent)
            except BaseException:
                with contextlib.suppress(OSError):
                    tmp_path.unlink()
                raise
        return path

    def _ensure_artifact_dir(self, path: Path) -> Path:
        with _DIGEST_LOCK:
            self._ensure_unsealed()
            path.mkdir(parents=True, exist_ok=True)
        return path

    # --- Core manifests ---

    def write_data_manifest(self, manifest: DataManifest) -> Path:
        """Write data_manifest.json."""
        path = self.run_dir / "data_manifest.json"
        return self._write_text(path, manifest.model_dump_json(indent=2))

    def write_seed_registry(self, registry: SeedRegistry) -> Path:
        """Write seed_registry.json."""
        path = self.run_dir / "seed_registry.json"
        return self._write_text(path, registry.model_dump_json(indent=2))

    def write_backend_versions(self, versions: BackendVersions) -> Path:
        """Write backend_versions.json."""
        path = self.run_dir / "backend_versions.json"
        return self._write_text(path, versions.model_dump_json(indent=2))

    def write_evidence_manifest(self, manifest: EvidenceManifest) -> Path:
        """Write evidence_manifest.json (Data Profiler output)."""
        path = self.run_dir / "evidence_manifest.json"
        return self._write_text(path, manifest.model_dump_json(indent=2))

    def write_initial_estimates(self, estimates: InitialEstimates) -> Path:
        """Write initial_estimates.json (keyed by candidate_id)."""
        path = self.run_dir / "initial_estimates.json"
        return self._write_text(path, estimates.model_dump_json(indent=2))

    def write_nca_diagnostics(self, diagnostics: list[NCASubjectDiagnostic]) -> Path:
        """Write nca_diagnostics.jsonl (one row per subject).

        Captures per-subject PKNCA-style QC outcomes (terminal lambda_z fit,
        AUC extrapolation, exclusion reasons) so reviewers can audit why
        the root initial estimates came from NCA, a literature prior, or
        defaults. One subject per line.
        """
        path = self.run_dir / "nca_diagnostics.jsonl"
        lines = [d.model_dump_json() for d in diagnostics]
        return self._write_text(path, "\n".join(lines) + ("\n" if lines else ""))

    def nca_plots_dir(self) -> Path:
        """Ensure and return diagnostics/nca_plots/ for per-subject NCA figures."""
        plots_dir = self.run_dir / "diagnostics" / "nca_plots"
        return self._ensure_artifact_dir(plots_dir)

    def write_split_manifest(self, split: SplitManifest) -> Path:
        """Write split_manifest.json."""
        path = self.run_dir / "split_manifest.json"
        return self._write_text(path, split.model_dump_json(indent=2))

    def write_policy_file(self, policy_data: dict[str, object]) -> Path:
        """Write policy_file.json (copy of the gate thresholds used for this run)."""
        path = self.run_dir / "policy_file.json"
        return self._write_text(path, json.dumps(policy_data, indent=2, default=str))

    def write_missing_data_directive(self, directive: MissingDataDirective) -> Path:
        """Write missing_data_directive.json.

        The directive is the policy-resolved missing-data plan for the run
        (covariate method, m budget, BLQ method, LLM guard, stability
        penalty, rationale). Included in the reproducibility bundle so
        downstream consumers can recover the exact decision that shaped
        the run without having to re-resolve against the policy file.
        """
        path = self.run_dir / "missing_data_directive.json"
        return self._write_text(path, directive.model_dump_json(indent=2))

    def write_imputation_stability(self, manifest: ImputationStabilityManifest) -> Path:
        """Write imputation_stability.json (MI runs only)."""
        path = self.run_dir / "imputation_stability.json"
        return self._write_text(path, manifest.model_dump_json(indent=2))

    def write_categorical_encoding_provenance(
        self, provenance: CategoricalEncodingProvenance
    ) -> Path:
        """Write categorical_encoding_provenance.json.

        Captures every column the auto-encoding pass inspected + the
        polarity actually applied. Lets reviewers trace exactly how a
        raw ``"male"`` / ``"female"`` column became 0/1 in the
        downstream FREM joint Ω entry, including whether the polarity
        came from auto-detection or a caller override (PRD §4.2.0).
        """
        path = self.run_dir / "categorical_encoding_provenance.json"
        return self._write_text(path, provenance.model_dump_json(indent=2))

    # --- Compiled specs ---

    def write_compiled_spec(
        self,
        spec: DSLSpec,
        initial_estimates: dict[str, float] | None = None,
    ) -> tuple[Path, Path | None]:
        """Write compiled_specs/{candidate_id}.json and .R.

        NODE specs are written as JSON only (no R lowering in Phase 1).

        Returns (json_path, r_path). r_path is None for NODE specs.
        """
        _validate_path_component(spec.model_id, "model_id")
        json_path = self._compiled_specs_dir / f"{spec.model_id}.json"
        self._write_text(json_path, spec.model_dump_json(indent=2))

        if spec.has_node_modules():
            return json_path, None

        r_path = self._compiled_specs_dir / f"{spec.model_id}.R"
        r_code = emit_nlmixr2(spec, initial_estimates=initial_estimates)
        self._write_text(r_path, r_code)

        return json_path, r_path

    # --- Results ---

    def write_backend_result(self, result: BackendResult) -> Path:
        """Write results/{candidate_id}_result.json."""
        _validate_path_component(result.model_id, "model_id")
        path = self._results_dir / f"{result.model_id}_result.json"
        return self._write_text(path, result.model_dump_json(indent=2))

    def write_seed_result(self, result: BackendResult, candidate_id: str, seed_index: int) -> Path:
        """Write results/{candidate_id}_seed_{n}_result.json."""
        _validate_path_component(candidate_id, "candidate_id")
        path = self._results_dir / f"{candidate_id}_seed_{seed_index}_result.json"
        return self._write_text(path, result.model_dump_json(indent=2))

    # --- Gate decisions ---

    def write_gate_decision(self, gate_result: GateResult, gate_number: int | str) -> Path:
        """Write gate_decisions/gate{n}_{candidate_id}.json.

        ``gate_number`` accepts ``int | str`` so callers can use ``"1b"`` for
        the Bayesian Gate 1 extension (avoiding overwriting the classical
        ``gate1_<id>.json``) and ``"2_5"`` for Gate 2.5 credibility (matching
        the ``gate2_5_*.json`` glob the inspect/diff CLIs already use).
        Numeric tokens are coerced via ``str(...)``; the value is fed
        through ``_validate_path_component`` so injection-via-tag is
        impossible.
        """
        _validate_path_component(gate_result.candidate_id, "candidate_id")
        gate_token = str(gate_number)
        _validate_path_component(gate_token, "gate_number")
        filename = f"gate{gate_token}_{gate_result.candidate_id}.json"
        path = self._gate_decisions_dir / filename
        return self._write_text(path, gate_result.model_dump_json(indent=2))

    # --- Search artifacts ---

    def append_search_trajectory(self, entry: SearchTrajectoryEntry) -> Path:
        """Append one line to search_trajectory.jsonl.

        The whole append happens under ``_DIGEST_LOCK`` so a concurrent
        ``seal()`` cannot snapshot the digest mid-write, and the post-
        write ``flush()``+``fsync()`` keeps the line on disk through a
        SIGKILL/OOM mid-pipeline (otherwise the buffered tail vanishes).
        """
        path = self.run_dir / "search_trajectory.jsonl"
        with _DIGEST_LOCK:
            # Post-seal appends would silently desync the bundle from the
            # _COMPLETE digest. Refuse so the footgun becomes a loud
            # error. The check lives under the lock to close the
            # is-sealed/append race window.
            if self.is_sealed():
                msg = (
                    f"cannot append to search_trajectory.jsonl: bundle {self.run_dir} "
                    "is sealed (would invalidate _COMPLETE digest)"
                )
                raise BundleAlreadySealedError(msg)
            with path.open("a") as f:
                f.write(entry.model_dump_json() + "\n")
                f.flush()
                os.fsync(f.fileno())
        return path

    def append_failed_candidate(self, entry: FailedCandidate) -> Path:
        """Append a line to failed_candidates.jsonl (locked + fsync'd).

        See :meth:`append_search_trajectory` for the lock / fsync rationale.
        """
        path = self.run_dir / "failed_candidates.jsonl"
        with _DIGEST_LOCK:
            if self.is_sealed():
                msg = (
                    f"cannot append to failed_candidates.jsonl: bundle {self.run_dir} "
                    "is sealed (would invalidate _COMPLETE digest)"
                )
                raise BundleAlreadySealedError(msg)
            with path.open("a") as f:
                f.write(entry.model_dump_json() + "\n")
                f.flush()
                os.fsync(f.fileno())
        return path

    def write_candidate_lineage(self, lineage: CandidateLineage) -> Path:
        """Write candidate_lineage.json (DAG of candidate parentage)."""
        path = self.run_dir / "candidate_lineage.json"
        return self._write_text(path, lineage.model_dump_json(indent=2))

    def write_search_graph(self, graph: SearchGraph) -> Path:
        """Write search_graph.json (enriched DAG for deep inspection)."""
        path = self.run_dir / "search_graph.json"
        return self._write_text(path, graph.model_dump_json(indent=2))

    def write_ranking(self, ranking: Ranking) -> Path:
        """Write ranking.json (full ordered candidate list from Gate 3)."""
        path = self.run_dir / "ranking.json"
        return self._write_text(path, ranking.model_dump_json(indent=2))

    def write_report_provenance(self, provenance: ReportProvenance) -> Path:
        """Write report_provenance.json (who/what generated each section)."""
        path = self.run_dir / "report_provenance.json"
        return self._write_text(path, provenance.model_dump_json(indent=2))

    # --- Credibility reports (per-candidate, Phase 2+) ---

    def _credibility_dir(self) -> Path:
        """Ensure and return the credibility/ subdirectory."""
        cred_dir = self.run_dir / "credibility"
        return self._ensure_artifact_dir(cred_dir)

    def write_credibility_report(self, report: CredibilityReport) -> Path:
        """Write credibility/{candidate_id}.json."""
        _validate_path_component(report.candidate_id, "candidate_id")
        path = self._credibility_dir() / f"{report.candidate_id}.json"
        return self._write_text(path, report.model_dump_json(indent=2))

    # --- LORO-CV results (Phase 3, Optimization lane) ---

    def _loro_cv_dir(self) -> Path:
        """Ensure and return the loro_cv/ subdirectory."""
        loro_dir = self.run_dir / "loro_cv"
        return self._ensure_artifact_dir(loro_dir)

    def write_loro_cv_result(self, result: LOROCVResult) -> Path:
        """Write loro_cv/{candidate_id}.json."""
        _validate_path_component(result.candidate_id, "candidate_id")
        path = self._loro_cv_dir() / f"{result.candidate_id}.json"
        return self._write_text(path, result.model_dump_json(indent=2))

    # --- Agentic trace (Phase 3, PRD §4.2.6) ---

    def _agentic_trace_dir(self) -> Path:
        """Ensure and return the agentic_trace/ subdirectory."""
        trace_dir = self.run_dir / "agentic_trace"
        return self._ensure_artifact_dir(trace_dir)

    def write_agentic_trace_input(self, inp: AgenticTraceInput) -> Path:
        """Write agentic_trace/{iteration_id}_input.json."""
        _validate_path_component(inp.iteration_id, "iteration_id")
        path = self._agentic_trace_dir() / f"{inp.iteration_id}_input.json"
        return self._write_text(path, inp.model_dump_json(indent=2))

    def write_agentic_trace_output(self, out: AgenticTraceOutput) -> Path:
        """Write agentic_trace/{iteration_id}_output.json."""
        _validate_path_component(out.iteration_id, "iteration_id")
        path = self._agentic_trace_dir() / f"{out.iteration_id}_output.json"
        return self._write_text(path, out.model_dump_json(indent=2))

    def write_agentic_trace_meta(self, meta: AgenticTraceMeta) -> Path:
        """Write agentic_trace/{iteration_id}_meta.json."""
        _validate_path_component(meta.iteration_id, "iteration_id")
        path = self._agentic_trace_dir() / f"{meta.iteration_id}_meta.json"
        return self._write_text(path, meta.model_dump_json(indent=2))

    def write_run_lineage(self, lineage: RunLineage) -> Path:
        """Write run_lineage.json (multi-run provenance, PRD §4.2.6)."""
        path = self.run_dir / "run_lineage.json"
        return self._write_text(path, lineage.model_dump_json(indent=2))

    # --- Bayesian artifacts (Phase 2+) ---

    def _bayesian_dir(self) -> Path:
        """Ensure and return the bayesian/ subdirectory."""
        bayes_dir = self.run_dir / "bayesian"
        return self._ensure_artifact_dir(bayes_dir)

    def write_prior_manifest(self, manifest: PriorManifest, candidate_id: str) -> Path:
        """Write bayesian/{candidate_id}_prior_manifest.json.

        FDA 2026 draft guidance requires the prior justification artifact to be
        persisted with the run. Callers that start from a list of DSL
        ``PriorSpec``s should prefer :meth:`write_prior_manifest_from_specs`
        so justification/DOI validation happens atomically with the write.
        """
        _validate_path_component(candidate_id, "candidate_id")
        path = self._bayesian_dir() / f"{candidate_id}_prior_manifest.json"
        return self._write_text(path, manifest.model_dump_json(indent=2))

    def write_prior_manifest_from_specs(
        self,
        specs: list[PriorSpec],
        candidate_id: str,
        *,
        policy_version: str,
        default_prior_policy: Literal["weakly_informative", "custom"] = "weakly_informative",
        justification_min_length: int = 50,
    ) -> Path:
        """Validate DSL ``PriorSpec``s and write their manifest atomically.

        The caller supplies the live list of priors (typically
        ``DSLSpec.priors``), the policy version, and the resolved
        ``justification_min_length`` (a per-lane policy override lands in
        Task 19). Every informative prior is checked for a minimum-length
        justification + a Crossref DOI; an aggregated ``ValueError`` is
        raised if any fail so reviewers see every issue in one pass.

        Nothing is written to disk if validation fails — this is important
        because the bundle is the unit of reproducibility and a partially-
        written ``bayesian/`` subtree would desync the ``_COMPLETE``
        digest. Callers can catch the ``ValueError`` and route to Gate 2
        failure-artifact emission (Task 19).
        """
        manifest = build_prior_manifest(
            specs,
            policy_version=policy_version,
            default_prior_policy=default_prior_policy,
            justification_min_length=justification_min_length,
        )
        return self.write_prior_manifest(manifest, candidate_id)

    def write_simulation_protocol(self, protocol: SimulationProtocol, candidate_id: str) -> Path:
        """Write bayesian/{candidate_id}_simulation_protocol.json.

        Prospective simulation protocol — locked before Gate 3 to prevent
        metric shopping (FDA 2026 operating-characteristics requirement).
        """
        _validate_path_component(candidate_id, "candidate_id")
        path = self._bayesian_dir() / f"{candidate_id}_simulation_protocol.json"
        return self._write_text(path, protocol.model_dump_json(indent=2))

    def write_mcmc_diagnostics(self, diagnostics: PosteriorDiagnostics, candidate_id: str) -> Path:
        """Write bayesian/{candidate_id}_mcmc_diagnostics.json.

        Deep-inspection tools expect diagnostics as a standalone artifact in
        addition to the nested ``BackendResult.posterior_diagnostics`` field.
        """
        _validate_path_component(candidate_id, "candidate_id")
        path = self._bayesian_dir() / f"{candidate_id}_mcmc_diagnostics.json"
        return self._write_text(path, diagnostics.model_dump_json(indent=2))

    def write_sbc_manifest(self, manifest: SBCManifest) -> Path:
        """Write artifacts/sbc/sbc_manifest.json (plan Task 26).

        Producer-side stub: orchestrators emit this with ``priors=[]`` on
        every Bayesian run so the artefact's *presence* signals the
        Bayesian path executed end-to-end. The nightly SBC runner
        (Task 27) overwrites the entries with the canonical 3-scenario
        rank-histogram results.

        Excluded from the sealed-bundle digest so a nightly rewrite does
        not invalidate ``_COMPLETE`` (see ``_DIGEST_EXCLUDED_RELATIVE_PATHS``).
        """
        sbc_dir = self.run_dir / "artifacts" / "sbc"
        sbc_dir.mkdir(parents=True, exist_ok=True)
        path = sbc_dir / _SBC_MANIFEST_FILENAME
        return self._write_text(path, manifest.model_dump_json(indent=2), allow_sealed=True)

    def write_loo_summary(self, summary: LOOSummary) -> Path:
        """Write bayesian/{candidate_id}_loo_summary.json (plan Task 18).

        Always emitted on a Bayesian run — when the Stan program lacks
        a ``log_lik`` per-observation declaration the harness still
        writes a ``status="not_computed"`` payload with the reason, so
        downstream gates can distinguish "skipped" from "missing
        artefact".
        """
        _validate_path_component(summary.candidate_id, "candidate_id")
        path = self._bayesian_dir() / f"{summary.candidate_id}_loo_summary.json"
        return self._write_text(path, summary.model_dump_json(indent=2))

    def write_reparameterization_recommendation(
        self,
        recommendation: ReparameterizationRecommendation,
    ) -> Path:
        """Write bayesian/{candidate_id}_reparameterization_recommendation.json.

        Advisory-only artifact. APMODE never switches parameterization
        silently (plan Task 25) — this file tells the operator which
        intervention the diagnostics suggest and why. The Gate 1
        Bayesian check (Task 17) surfaces the file path in its failure
        message so the recommendation stays in the audit trail.
        """
        _validate_path_component(recommendation.candidate_id, "candidate_id")
        filename = f"{recommendation.candidate_id}_reparameterization_recommendation.json"
        path = self._bayesian_dir() / filename
        return self._write_text(path, recommendation.model_dump_json(indent=2))

    def write_prior_data_conflict(self, artifact: PriorDataConflict) -> Path:
        """Write bayesian/{candidate_id}_prior_data_conflict.json (plan Task 20).

        Always emitted on a Bayesian run when the lane policy enables
        the check — when the harness cannot run the prior-only Stan
        pass it still writes a ``status="not_computed"`` payload so the
        absence of computation is recorded. Gate 2 reads this artefact
        back via :func:`evaluate_gate2`'s ``prior_data_conflict``
        keyword.
        """
        _validate_path_component(artifact.candidate_id, "candidate_id")
        path = self._bayesian_dir() / f"{artifact.candidate_id}_prior_data_conflict.json"
        return self._write_text(path, artifact.model_dump_json(indent=2))

    def write_prior_sensitivity(self, artifact: PriorSensitivity) -> Path:
        """Write bayesian/{candidate_id}_prior_sensitivity.json (plan Task 21).

        Same emission contract as
        :meth:`write_prior_data_conflict`: the file is the audit-trail
        carrier, ``status`` distinguishes a real result from a recorded
        skip, and Gate 2 consumes it via
        :func:`evaluate_gate2`'s ``prior_sensitivity`` keyword.
        """
        _validate_path_component(artifact.candidate_id, "candidate_id")
        path = self._bayesian_dir() / f"{artifact.candidate_id}_prior_sensitivity.json"
        return self._write_text(path, artifact.model_dump_json(indent=2))

    def write_sampler_config(self, config: SamplerConfig, candidate_id: str) -> Path:
        """Write bayesian/{candidate_id}_sampler_config.json.

        The persisted ``SamplerConfig`` is the exact configuration cmdstanpy
        was asked to use (chains, warmup, sampling, adapt_delta,
        max_treedepth, seed, etc.). Paired with ``backend_versions.json``
        and the ``save_cmdstan_config=True`` CSV hash set, this is enough
        to reconstruct the run (cmdstanpy issue #848).
        """
        _validate_path_component(candidate_id, "candidate_id")
        path = self._bayesian_dir() / f"{candidate_id}_sampler_config.json"
        return self._write_text(path, config.model_dump_json(indent=2))

    def copy_posterior_draws(self, source: Path, candidate_id: str) -> Path:
        """Copy posterior_draws.parquet from the harness work_dir into the bundle.

        Returns the bundle-relative path that should be stored on
        ``BackendResult.posterior_draws_path`` so the reference is durable.
        """
        import shutil

        _validate_path_component(candidate_id, "candidate_id")
        dest = self._bayesian_dir() / f"{candidate_id}_draws.parquet"
        with _DIGEST_LOCK:
            self._ensure_unsealed()
            shutil.copy2(source, dest)
        return dest

    def write_posterior_summary(
        self,
        candidate_id: str,
        summary_df: Any,
    ) -> Path:
        """Write a long-form posterior summary to ``{cid}_posterior_summary.parquet``.

        Expects a pandas DataFrame with the canonical column set
        ``{param, rhat, ess_bulk, ess_tail, mean, sd, q05, q50, q95}``.
        One row per parameter. Callers driving cmdstanpy should rename
        ``CmdStanMCMC.summary()`` columns (``Mean``/``StdDev``/``5%``/...)
        to match before invoking this emitter — the strict schema is the
        point, since downstream Gate-1 Bayesian checks read these fields
        by name.
        """
        import pyarrow as pa
        import pyarrow.parquet as pq

        _validate_path_component(candidate_id, "candidate_id")

        canonical = (
            "param",
            "rhat",
            "ess_bulk",
            "ess_tail",
            "mean",
            "sd",
            "q05",
            "q50",
            "q95",
        )
        actual = set(getattr(summary_df, "columns", []))
        missing = set(canonical) - actual
        if missing:
            msg = f"summary_df missing required columns: {sorted(missing)}"
            raise ValueError(msg)

        table = pa.Table.from_pandas(summary_df[list(canonical)], preserve_index=False)
        dest = self._bayesian_dir() / f"{candidate_id}_posterior_summary.parquet"
        with _DIGEST_LOCK:
            self._ensure_unsealed()
            pq.write_table(table, dest)
        return dest

    def write_posterior_draws(
        self,
        candidate_id: str,
        draws_by_param: dict[str, object],
        thin_every: int = 1,
    ) -> Path:
        """Write thinned posterior draws to ``{cid}_posterior_draws.parquet``.

        In-memory counterpart to ``copy_posterior_draws`` — used when the
        caller already has draws as numpy arrays (e.g. when tests synthesise
        draws without running cmdstanpy). The layout is long-form
        ``(chain, iter, param, value)`` so parameters can be appended over
        multiple calls without schema divergence.

        Args:
            candidate_id: Safe path component identifying the candidate.
            draws_by_param: Mapping ``param_name -> ndarray(chains, iters)``.
                Each array must have ``ndim == 2``.
            thin_every: Retain every ``thin_every``-th iteration per chain.
                Default 1 (no thinning).

        Returns:
            Absolute path to the written parquet file.
        """
        import numpy as np
        import pyarrow as pa
        import pyarrow.parquet as pq

        _validate_path_component(candidate_id, "candidate_id")
        if thin_every < 1:
            msg = f"thin_every must be >= 1, got {thin_every}"
            raise ValueError(msg)

        rows_chain: list[int] = []
        rows_iter: list[int] = []
        rows_param: list[str] = []
        rows_value: list[float] = []
        for name, arr_obj in draws_by_param.items():
            arr = np.asarray(arr_obj)
            if arr.ndim != 2:
                msg = f"draws for {name!r} must be 2-D (chains, iters); got shape {arr.shape}"
                raise ValueError(msg)
            thinned = arr[:, ::thin_every]
            n_chains, n_iters = thinned.shape
            for c in range(n_chains):
                for i in range(n_iters):
                    rows_chain.append(c)
                    rows_iter.append(i)
                    rows_param.append(name)
                    rows_value.append(float(thinned[c, i]))

        table = pa.table(
            {
                "chain": rows_chain,
                "iter": rows_iter,
                "param": rows_param,
                "value": rows_value,
            }
        )
        dest = self._bayesian_dir() / f"{candidate_id}_posterior_draws.parquet"
        with _DIGEST_LOCK:
            self._ensure_unsealed()
            pq.write_table(table, dest)
        return dest
